apiVersion: v1
kind: Service
metadata:
  name: gcp-essentials-serv
spec:
  type: LoadBalancer
  selector:
    app: gcp-essentials-serv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
